### ISSUE TITLE
why is a "status" subresource required to be declared for KDC?

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#176] opened 2019-07-27 05:28 UTC
Observed by Don in his development setup.

On the master branch, this is not required. And for various reasons we actually are _not_ using the status subresource, but instead just treating status as a property with an object value.

First thing is to get clear about what the failure mode is, then investigate the difference between that branch and the main branch (or between Don's setup and others).

**Comment by don-milos** [comment] 2019-07-30 18:37
When I remove the subresources property from the KD CRD file updates to the KD Cluster status fails. Something in the newer version of the operator-sdk requires it. I don't see the harm of including it in our CR definition since it's empty.

Line that fails:
       err := client.Status().Update(context.TODO(), cr)
Failure:
{
    "Request.Name": "centos7-persistent",
    "Request.Namespace": "default",
    "error": "the server could not find the requested resource (put kubedirectorclusters.kubedirector.bluedata.io centos7-persistent)",
    "level": "error",
    "logger": "controller_kubedirectorcluster",
    "msg": "failed to update status",
    "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr/zapr.go:128
    github.com/bluek8s/kubedirector/pkg/shared.LogError
        /alt/root/go/src/github.com/bluek8s/kubedirector/pkg/shared/logging.go:78
    github.com/bluek8s/kubedirector/pkg/executor.UpdateStatus
        /alt/root/go/src/github.com/bluek8s/kubedirector/pkg/executor/cluster.go:49
    github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster.func1
        /alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:59
    github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster
        /alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:107
    github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).Reconcile
        /alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go:105
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
    k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
    k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
    k8s.io/apimachinery/pkg/util/wait.Until
        /alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"

    "ts": 1564509080.770766
}

**Comment by joel-bluedata** [comment] 2019-08-01 17:11
It looks like client.Status() specifically is getting a handle on the status subresource of an object. Therefore since we're trying to update the subresource in that line of code, it makes sense that it would fail if there's not a subresource declared.

My first reaction is that any place where we're doing client.Status().Update, we should be doing client.Update instead, since for various reasons we've been avoiding using a status subresource. That would mean that we should be doing our PATCH-equivalent process to update status (since the original code was using PATCH).

For the status object in particular though, issue #178 describes one complication in that we MUST succeed in our update before exiting the handler. So if we got a resource version conflict in our update we couldn't just bail out and wait for the next handler iteration to try again. That means we have two solutions to choose from:

1) Use a read-modify-write attempt loop inside the UpdateStatus function.

or

2) It's finally time to move to using a status subresource (and close issue #37 as a bonus).

If we do move to using a status subresource, I think one of the comments on issue #37 is incorrect ... we can't/shouldn't depend on RBAC to protect it from other clients. We still need to continue using our validator to protect it. In that case we need to make sure that the validator still kicks in to protect the status resource regardless of how a client chooses to write status to our object... e.g. what happens if a client tries to write to a "status" property of the cluster, and what happens if they try to write to the "status" subresource of the cluster.

**Comment by joel-bluedata** [comment] 2019-08-01 17:13
BTW when grepping the code I found a couple of other uses of client.Status().Update that seem weird, in UpdatePodService. Those are almost definitely wrong since we're trying to update the service object itself and not any status sub-object on that service. Also one of the resulting error log messages has a bad message and event reason, probably a C&P bug. I can file a separate issue for that.

**Comment by don-milos** [comment] 2019-08-03 19:02
The  client.Status().Update() calls in executor/service.go are definitely C&P bugs and will be fixed.

I'm not so sure about the calls in executor/cluster.go/UpdateStatus() though. When I changed those calls in UpdateStatus() to client.Update() the StatusGen/GenerationUID in the Status was not updated. I think the status was dropped per the last line in this comment below.

I can't point to anything definitive but the documentation I've looked at seem to allude that the CR status is now considered a subresource. I'm not referring to subresources / status. I'm referring to the spec and status structs that are part of the resource.

If you look at the K8s documentation here: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md you'll find the following statements.

- Update does *not* update the resource's status subresource
- When updating the status subresource from the client, the StatusWriter must be used which can be gotten with Status().

Even though it's not official K8s documentation I found this https://www.oreilly.com/library/view/programming-kubernetes/9781492047094/ch04.html:

- Resources (including custom resources) that have a /status subresource have changed semantics, also for the main resource endpoint:
- They ignore changes to the status on the main HTTP endpoint during create (the status is just dropped during a create) and updates. (this line is confirmed by my observations)

**Comment by joel-bluedata** [comment] 2019-08-07 21:41
Right, just to be clear, I think we would need to have consistency by following one of these two approaches:

1) If we do NOT declare a status subresource, then our code should use client.Update even when modifying the status property. This should mimic our old behavior.

2) If we DO declare a status subresource, then our code should use client.Status.Update.

If we do some other combination of things then it's probably to be expected that it would fail. I'm suggesting I think we should stick with 1) for now. When you mention: "When I changed those calls in UpdateStatus() to client.Update() the StatusGen/GenerationUID in the Status was not updated", was this with a status subresource declared or not?

**Comment by don-milos** [comment] 2019-08-08 00:08
When I tried changing the calls to client.Update() and the StatusGen/GenerationUID in the Status was not updated, it was with the status.subresource deleted. From my observations it appears that client.Update() does not update the Status property in the resource.

In other words we don't really have a choice. Without staus.subresource declared, client.Status().Update() fails and client.Update() doesn't update the Status property.

**Comment by joel-bluedata** [comment] 2019-08-08 17:56
OK, so be it. Therefore we will declare a status resource and use client.Status().Update().

This means:
* When the new operator SDK branch is merged into master we can also close issue #37.
* We will update our docs to require some k8s version 1.10 or later as the floor. (Maybe there are other reasons we should lift the floor even more, like to 1.12.)

We need to make sure we have specific answers to the following questions. I think you answered them as part of the discussion above, at least partly, but let's make sure:
* Are other clients prevented from writing to the KDCluster status as a property (as opposed to a sub-resource)?
* Does the validator still protect against other, non-KubeDirector clients writing to the KDCluster status sub-resource?

**Comment by don-milos** [comment] 2019-08-09 22:57
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource

**Status subresource**

When the status subresource is enabled, the /status subresource for the custom resource is exposed.
- The status and the spec stanzas are represented by the .status and .spec JSONPaths respectively inside of a custom resource.
- PUT requests to the /status subresource take a custom resource object and ignore changes to anything except the status stanza.
- PUT requests to the /status subresource only validate the status stanza of the custom resource.
- PUT/POST/PATCH requests to the custom resource ignore changes to the status stanza.
- The .metadata.generation value is incremented for all changes, except for changes to .metadata or .status.

> Are other clients prevented from writing to the KDCluster status as a property (as opposed to a sub-resource)?

Yes, the fourth bullet above says that request to update the KDCluster will ignore the status stanza of the CR. We actually verified that the validation still takes place when you had me try using Update() instead of Status().Update() in the UpdateStatus() function. That experiment failed because Update() didn't write the status stanza containing the new GenerationUID.

> Does the validator still protect against other, non-KubeDirector clients writing to the KDCluster status sub-resource?

Yes. The third bullet above says the PUT requests to the status subresource will be "validated". Therefore the status will be protected by the statusgen/GenerationUID as it is today.

**Comment by joel-bluedata** [comment] 2019-08-12 18:44
All righty!

**Closed** 2019-08-12 18:44 UTC
Labels: Priority: High, Project: Operator SDK, Type: Bug
