### ISSUE TITLE
service not auto start after delete the pod

### ISSUE THREAD

**Issue by Pandoraemon** [bluek8s/kubedirector#335] opened 2020-06-17 03:34 UTC
Hi, I test with the newest master branch and found service not auto start after delete the pod which should work right on 0.4.1.

**Comment by joel-bluedata** [comment] 2020-06-17 14:42
Can you be more specific about the issue? E.g. which kdapp, the content of your kdcluster file, and the steps taken to reproduce the problem.

**Comment by Pandoraemon** [comment] 2020-06-18 01:07
it's cdh6  and I use deploy/example_clusters/cr-cluster-cdh632cm-stor.yaml
 After the app is start and I delete the primary pod use kubectl delete pod cmd.
when the deleted pod start again, the services like mysqld, cloudera-scm-server, cloudera-scm-agent not start. I need to start it manually.

**Comment by joel-bluedata** [comment] 2020-06-18 17:19
Probably need the kdapp author @omhpe to take a look here. I'm not sure yet that I see an issue.

Generally speaking, if a pod using persistent storage is restarted, KD does not attempt to restart the services. It is assumed that this is the container's responsibility, either through systemd or through the container's entrypoint command.

So my initial assumption was that this could be some sort of failure to properly set up the service for restart when the container restarts. Since this app uses systemd, maybe the service was not enabled through systemctl. It could be the case though that some other enabled service would be responsible for starting it.

I created a kdcluster and exec'd into the primary node to look around.

I don't see mysqld or cloudera-scm-server running at all. Is it really true that these should be on "primary"? I would have expected those to only be on "cmserver".

I do see cloudera-scm-agent. It is running, but it is not *enabled*, so I'm not surprised that it doesn't auto-restart.

In the startscript, I see code that does "systemctl start cloudera-scm-agent", but nothing that does "systemctl enable". This seems like a problem. Similarly for other services.

Some of the kdapp setup packages use a common macros file, which defines a REGISTER_START_SERVICE_SYSCTL macro that both starts and enables a service. It's fine to not use macros and to do things more finegrained/explicitly in the startscript, but as far as I know the service does need to be systemctl-enabled if it needs to restart when the pod restarts. The only time this would not be the case would be if some other auto-restarted service would be responsible for eventually starting it up.

Anyway, over to @omhpe for investigation/fixing. I think this is a little bit of a red flag that this issue needs to be double-checked in other recently added apps.

**Comment by riteshja** [comment] 2020-06-18 17:35
Hi @joel-bluedata 

I wonder how CDH 6.x is working in 0.4.1. CDH 6.x scripts never did "systemctl enable".  Anyway, we will take a look through each of our apps and add "systemctl enable".

**Comment by joel-bluedata** [comment] 2020-06-18 17:41
OK, but only if that's the correct thing to do! For example if cloudera manager is itself going to explicitly restart other services when it comes up, then only it needs to be enabled. I don't know myself what the correct situation is off the top of my head -- presumably/hopefully there's a playbook for setting up the app that indicates which services need to be enabled for auto restart. And in the case of Cloudera at least you could also look at what the old EPIC app does.

**Comment by riteshja** [comment] 2020-06-18 17:52
Yup. It would be per case basis. As far as i remember, Cloudera EPIC apps' behavior is that you have to manually restart all the services. Only cloudera-manager, cloudera-agent and mysql  are systemctl-enabled. And cloudera-manager does not explicitly restart the services. Will double check, though

Most of the other apps don't have a manager kind of entity, and there needs to be a proper sequencing that needs to happen when restarting the services. For them, on pod reboot, behavior is unpredictable and very hard to automate.

**Comment by joel-bluedata** [comment] 2020-06-18 18:07
Hmm. IIRC the old EPIC apps used the REGISTER_START_SERVICE_SYSCTL macro which in that case would register the service with vAgent rather than systemctl... but the effect on container restart is the same, i.e. every service is restarted without any particular sequencing. In fact the vAgent restarting would have been even more free-form than systemctl restarting since there would be no way to declare inter-service dependencies there.

**Comment by riteshja** [comment] 2020-06-18 18:36
That's right! Vagent also does not guarantee any ordering on container restart. That's why, most of the EPIC apps behave unpredictably when rebooted. Except those that have a manager(manual intervention still required) and the spark standalone apps(because they don't care about ordering. Spark workers just find the spark master through heartbeats).

So, even if we systemctl-enable services in roles for apps without managers or even with managers, there still might be some manual effort involved to get the system back in order. 

I expect the spark245 app and ELK app to survive pod reboots without any manual intervention.

**Closed** 2020-06-19 15:24 UTC
Labels: Priority: Blocker, Project: Example Apps, Type: Bug
